// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: protobuf/proto/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用code
type Code int32

const (
	Code_Unknown                 Code = 0   //未知
	Code_Ok                      Code = 1   //成功
	Code_TokenInvalid            Code = 401 //token失效
	Code_ParameterError          Code = 402 //参数错误
	Code_Exists                  Code = 403 //已存在
	Code_NotExists               Code = 404 //不存在
	Code_SystemError             Code = 405 //系统错误
	Code_DbError                 Code = 406 //数据库错误
	Code_StatusError             Code = 407 //状态错误
	Code_AmountInsufficientError Code = 408 //余额不足
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:   "Unknown",
		1:   "Ok",
		401: "TokenInvalid",
		402: "ParameterError",
		403: "Exists",
		404: "NotExists",
		405: "SystemError",
		406: "DbError",
		407: "StatusError",
		408: "AmountInsufficientError",
	}
	Code_value = map[string]int32{
		"Unknown":                 0,
		"Ok":                      1,
		"TokenInvalid":            401,
		"ParameterError":          402,
		"Exists":                  403,
		"NotExists":               404,
		"SystemError":             405,
		"DbError":                 406,
		"StatusError":             407,
		"AmountInsufficientError": 408,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_proto_common_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_protobuf_proto_common_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{0}
}

type ReqHead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	UserId int32  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ReqHead) Reset() {
	*x = ReqHead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqHead) ProtoMessage() {}

func (x *ReqHead) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqHead.ProtoReflect.Descriptor instead.
func (*ReqHead) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *ReqHead) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ReqHead) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RepHead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code Code   `protobuf:"varint,1,opt,name=code,proto3,enum=common.Code" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *RepHead) Reset() {
	*x = RepHead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepHead) ProtoMessage() {}

func (x *RepHead) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepHead.ProtoReflect.Descriptor instead.
func (*RepHead) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *RepHead) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_Unknown
}

func (x *RepHead) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BasicReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head *ReqHead   `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Data *anypb.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BasicReq) Reset() {
	*x = BasicReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicReq) ProtoMessage() {}

func (x *BasicReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicReq.ProtoReflect.Descriptor instead.
func (*BasicReq) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *BasicReq) GetHead() *ReqHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *BasicReq) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_protobuf_proto_common_proto protoreflect.FileDescriptor

var file_protobuf_proto_common_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x38, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x48, 0x65, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x07, 0x72, 0x65,
	0x70, 0x48, 0x65, 0x61, 0x64, 0x12, 0x20, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x59, 0x0a, 0x08, 0x62, 0x61, 0x73,
	0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x72, 0x65, 0x71,
	0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x2a, 0xb0, 0x01, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6b,
	0x10, 0x01, 0x12, 0x11, 0x0a, 0x0c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x6e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x10, 0x91, 0x03, 0x12, 0x13, 0x0a, 0x0e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x92, 0x03, 0x12, 0x0b, 0x0a, 0x06, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x73, 0x10, 0x93, 0x03, 0x12, 0x0e, 0x0a, 0x09, 0x4e, 0x6f, 0x74, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x73, 0x10, 0x94, 0x03, 0x12, 0x10, 0x0a, 0x0b, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x95, 0x03, 0x12, 0x0c, 0x0a, 0x07, 0x44, 0x62, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x10, 0x96, 0x03, 0x12, 0x10, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x97, 0x03, 0x12, 0x1c, 0x0a, 0x17, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x6e, 0x73, 0x75, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x10, 0x98, 0x03, 0x42, 0x1c, 0x5a, 0x1a, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x62, 0x73, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_proto_common_proto_rawDescOnce sync.Once
	file_protobuf_proto_common_proto_rawDescData = file_protobuf_proto_common_proto_rawDesc
)

func file_protobuf_proto_common_proto_rawDescGZIP() []byte {
	file_protobuf_proto_common_proto_rawDescOnce.Do(func() {
		file_protobuf_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_proto_common_proto_rawDescData)
	})
	return file_protobuf_proto_common_proto_rawDescData
}

var file_protobuf_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_proto_common_proto_goTypes = []interface{}{
	(Code)(0),         // 0: common.Code
	(*ReqHead)(nil),   // 1: common.reqHead
	(*RepHead)(nil),   // 2: common.repHead
	(*BasicReq)(nil),  // 3: common.basicReq
	(*anypb.Any)(nil), // 4: google.protobuf.Any
}
var file_protobuf_proto_common_proto_depIdxs = []int32{
	0, // 0: common.repHead.code:type_name -> common.Code
	1, // 1: common.basicReq.head:type_name -> common.reqHead
	4, // 2: common.basicReq.data:type_name -> google.protobuf.Any
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protobuf_proto_common_proto_init() }
func file_protobuf_proto_common_proto_init() {
	if File_protobuf_proto_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_proto_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqHead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepHead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_proto_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_proto_common_proto_goTypes,
		DependencyIndexes: file_protobuf_proto_common_proto_depIdxs,
		EnumInfos:         file_protobuf_proto_common_proto_enumTypes,
		MessageInfos:      file_protobuf_proto_common_proto_msgTypes,
	}.Build()
	File_protobuf_proto_common_proto = out.File
	file_protobuf_proto_common_proto_rawDesc = nil
	file_protobuf_proto_common_proto_goTypes = nil
	file_protobuf_proto_common_proto_depIdxs = nil
}
